name: Deploy CDK Application

on:
  push:
    branches:
      - main

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Save node_modules as artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: node_modules

  deploy:
    name: Deploy CDK Stack
    needs: install # Garantir que o job "install" seja executado antes
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Restore node_modules from artifact
        uses: actions/download-artifact@v3
        with:
          name: node-modules
          path: node_modules

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CDK Stack
        run: npx cdk deploy --require-approval never

  test:
    name: Test Deployment (Optional)
    runs-on: ubuntu-latest
    needs: deploy # Aguarda o job "deploy" ser concluído
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Verify Deployment
        run: echo "Test logic here, e.g., AWS CLI checks"
